root = "."
tmp_dir = ".air_tmp"

[build]
pre_cmd = [
  "pnpx tailwindcss -i ./static/input.css -o ./static/output.css",
  "templ generate",
]
cmd = "go build -o .air_tmp/main cmd/main.go"
bin = ".air_tmp/main"
include_ext = ["go", "templ"]
exclude_dir = [".air_tmp"]
exclude_regex = [".*_templ.go"]
stop_on_error = true
