version: "3"

env:
  ENV: local

dotenv: [".env", ".env.{{.ENV}}"]

tasks:
  run:
    desc: "Runs the server and reloads on every file change"
    cmds:
      - air
  kill:
    desc: "Kills zombie processes"
    cmds:
      - kill -9 $(lsof -t -i:1234)
